version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./app:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./app:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  db-test:
    build: ./infra/mysql-test
    volumes:
      - db-store:/db-test/var/lib/mysql
    ports:
      - 3000:3306

volumes:
  db-store: