version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./app:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work